dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: hybr-eat
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.29
- name: hybrit-app-generic-env-config
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.13
- name: redis-db
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.8
